"""Add email to User

Revision ID: 51a38bfda90c
Revises: 20251221_000001
Create Date: 2026-01-28 05:19:05.359210

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51a38bfda90c'
down_revision = '20251221_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_posts', 'author',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('community_posts', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('progress_stats', 'history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('question_feedback', 'improvements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('question_feedback_report_id_fkey'), 'question_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'question_feedback', 'reports', ['report_id'], ['id'])
    op.alter_column('reports', 'radarData',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'timelineData',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'fillerWordsAnalysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'pacingAnalysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'behavioralAnalysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'swot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('reports', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('transcript_entries_report_id_fkey'), 'transcript_entries', type_='foreignkey')
    op.create_foreign_key(None, 'transcript_entries', 'reports', ['report_id'], ['id'])
    op.add_column('users', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'transcript_entries', type_='foreignkey')
    op.create_foreign_key(op.f('transcript_entries_report_id_fkey'), 'transcript_entries', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reports', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('reports', 'swot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('reports', 'behavioralAnalysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('reports', 'pacingAnalysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('reports', 'fillerWordsAnalysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('reports', 'timelineData',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('reports', 'radarData',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(None, 'question_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('question_feedback_report_id_fkey'), 'question_feedback', 'reports', ['report_id'], ['id'], ondelete='CASCADE')
    op.alter_column('question_feedback', 'improvements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('progress_stats', 'history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('community_posts', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('community_posts', 'author',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
